### ISSUE TITLE
"read_description_json" virker ikke med json-tekstrenger fra versjon 1.1.0.

### ISSUE THREAD

**Issue by Bjoern-Rapp** [statisticsnorway/dapla-statbank-client#105]
Funksjonen feiler nå fra linje 235: `if Path(json_path_or_str).exists():` med feilmeldingen "OSError: [Errno 36] File name too long", hvis du sender funksjonen en lagret tabellbeskrivelse som en JOSN tekstreng.

**Comment by aecorn** [comment]
Ok, så du prøver å sende en json-tekststreng som "path" inn i client.read_description_json()?
Lurer på om det beste her er å catche OSErroren, eller hva tenker du?
